steps:
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['run', 'whalesay-job-$BUILD_ID', '--image=docker/whalesay', '--', 'cowsay', 'Hello, world!']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=meu-cluster-gke'
substitutions:
  _MY_CUSTOM_VARIABLE: 'custom-value'
